### ISSUE TITLE
The sum is exposed in the console

### ISSUE THREAD

**Issue by RizqiSyahrendra** [DanielL-01/sum_625#1]
In case you want to fix it, or idk if you just put it on purpose for fun xD 
![image](https://github.com/DanielL-01/sum_625/assets/19841840/601c6196-aaad-45a9-bc67-18e4c72df12c)

![image](https://github.com/DanielL-01/sum_625/assets/19841840/ead1694d-39ac-4ad8-82b5-175dda9475a4)

Btw keren langsung kepikiran bikin webnya setelah nonton clash of champion, great job!

**Comment by DanielL-01** [comment]
Hello kak, thank you for trying my website kak, and thank you as well for reminding me about the console.log hehe. If you have any more suggestions, feel free to leave in the comments. Thank you so much kak.

**Comment by RizqiSyahrendra** [comment]
I'll close this issue since it's been fixed, thanks, keep it up!
